
### create user

POST http://localhost:3200/api/1/users/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG0iLCJhZGRyZXNzIjoiYXNkc2FkYXNkIiwicGhvbmUiOiIwNTQtNjk4NTkzMiIsImVtYWlsIjoiYWRtQHdhbGxhLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDktMTRUMTE6MDE6NDYuNjIzWiIsInVwZGF0ZWRBdCI6IjIwMjAtMTEtMTlUMTU6NDA6MDAuOTgzWiJ9LCJpYXQiOjE2MDg0ODgwNTAsImV4cCI6MTYwODg0ODA1MH0.wyYhpqyt86XlrVhtlrZ7W_ZsHxoFz3u1AvZnzIoJzME


{
  
 "userId":"305440894",
 "userType":"1",
 "fullName":"Koral Mazor",
 "address":"Hibat Zion",
 "phone":"+97-2506933706",
 "email":"koralmazor@gmail.com",
 "password":"123456"
  
}

### get the connected user ( Token must be included )
GET http://localhost:3200/api/1/users/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG0iLCJhZGRyZXNzIjoiYXNkc2FkYXNkIiwicGhvbmUiOiIwNTQtNjk4NTkzMiIsImVtYWlsIjoiYWRtQHdhbGxhLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDktMTRUMTE6MDE6NDYuNjIzWiIsInVwZGF0ZWRBdCI6IjIwMjAtMTEtMTlUMTU6NDA6MDAuOTgzWiJ9LCJpYXQiOjE2MDg1MzYxNzUsImV4cCI6MTYwODg5NjE3NX0.QhNtpOXheg64dKIZiKW_xxvDTgmXndQIXdTtgqqyoVU

### delete connected user
DELETE  http://localhost:3200/api/1/users/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG1pbiIsImFkZHJlc3MiOiJhc2RzYWRhc2QiLCJwaG9uZSI6IjA1NC02OTg1OTMzIiwiZW1haWwiOiJhZG1Ad2FsbGEuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIiwidXBkYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIn0sImlhdCI6MTYwMTA0NzA4OCwiZXhwIjoxNjAxNDA3MDg4fQ.FnV-SqAkOyY_APLKpQu8Gnh10yvBTPCdVHgeO4oaP3M


### login
POST http://localhost:3200/api/1/users/login
Content-Type: application/json


{
 
  "userId": "305440894",
  "password": "123456"
  
}

### get all users
GET http://localhost:3200/api/1/users/get/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEwMjg4MTEzLCJleHAiOjE2MTA2NDgxMTN9._FgRbHZMwvisAcyDDWu92HZvuJGx3BqHMdrtRJ858RY

### edit user
PATCH  http://localhost:3200/api/1/users/edit/111111111
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG1pbiIsImFkZHJlc3MiOiJhc2RzYWRhc2QiLCJwaG9uZSI6IjA1NC02OTg1OTMzIiwiZW1haWwiOiJhZG1Ad2FsbGEuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIiwidXBkYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIn0sImlhdCI6MTYwMjI1MDgzMiwiZXhwIjoxNjAyNjEwODMyfQ.EHyo3ONWJJLUQTQDOTFvUh1epthPL2fiWbf2bbkxNuM

{
    "userType": "1",
    "fullName": "Tomer Zaidler",
    "address": "Hertzel",
    "phone": "0501234567",
    "email": "tomer@mail.com"
}

### delete user by id
DELETE  http://localhost:3200/api/1/users/delete/333333333
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG1pbiIsImFkZHJlc3MiOiJhc2RzYWRhc2QiLCJwaG9uZSI6IjA1NC02OTg1OTMzIiwiZW1haWwiOiJhZG1Ad2FsbGEuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIiwidXBkYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIn0sImlhdCI6MTYwMTA0NzA4OCwiZXhwIjoxNjAxNDA3MDg4fQ.FnV-SqAkOyY_APLKpQu8Gnh10yvBTPCdVHgeO4oaP3M


### get chillers
GET  http://localhost:3200/api/1/chillers/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMDQyMzIwLCJleHAiOjE2MTM0MDIzMjB9.EfZv0pT5FG16E0cSiF0ECBB48cjF_sFkj4Z_4Sy1WQ8

### get chillers settings
GET  http://localhost:3200/api/1/chillers/get/settings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMDQyMzIwLCJleHAiOjE2MTM0MDIzMjB9.EfZv0pT5FG16E0cSiF0ECBB48cjF_sFkj4Z_4Sy1WQ8



### get chiller by id
GET  http://localhost:3200/api/1/chillers/get/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMDQyMzIwLCJleHAiOjE2MTM0MDIzMjB9.EfZv0pT5FG16E0cSiF0ECBB48cjF_sFkj4Z_4Sy1WQ8

### create chiller
POST  http://localhost:3200/api/1/chillers/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG1pbiIsImFkZHJlc3MiOiJhc2RzYWRhc2QiLCJwaG9uZSI6IjA1NC02OTg1OTMzIiwiZW1haWwiOiJhZG1Ad2FsbGEuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIiwidXBkYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIn0sImlhdCI6MTYwMjI0NzczMywiZXhwIjoxNjAyNjA3NzMzfQ.VKK69AQUUq_vWIqLWE74QoKWfQmM1tGsvBSwux7xfYI

{
  "host": "172.13.11.192",
  "port": "901",
  "unitId": "1"
}

### delete chiller
DELETE  http://localhost:3200/api/1/chillers/delete/chiller1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNWY0ZDlhMTI3ODMwNDM0MDVlNjViZSIsImlkIjoiMjIyMjIyMjIyIiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJBZG1pbiIsImFkZHJlc3MiOiJhc2RzYWRhc2QiLCJwaG9uZSI6IjA1NC02OTg1OTMzIiwiZW1haWwiOiJhZG1Ad2FsbGEuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIiwidXBkYXRlZEF0IjoiMjAyMC0wOS0xNFQxMTowMTo0Ni42MjNaIn0sImlhdCI6MTYwMjI0NzczMywiZXhwIjoxNjAyNjA3NzMzfQ.VKK69AQUUq_vWIqLWE74QoKWfQmM1tGsvBSwux7xfYI


### get chiller history
GET http://localhost:3200/api/1/chillers/history/1/2020-11-01/2020-12-31
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMDQyMzIwLCJleHAiOjE2MTM0MDIzMjB9.EfZv0pT5FG16E0cSiF0ECBB48cjF_sFkj4Z_4Sy1WQ8

### get chiller data range
GET http://localhost:3200/api/1/chillers//daterange/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEyODkwNTU4LCJleHAiOjE2MTMyNTA1NTh9.sQ-M-FAkmdv-i3pHtymvftjPaJIFf1PCJRdr4o97o84


### get counters Devices
GET  http://localhost:3200/api/1/counters/get/devices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMzMyMjM3LCJleHAiOjE2MTM2OTIyMzd9.2uszWN7KDtAg0gYFo0yJpPrLK_TyMeLhmrC0ArmCogs

### get counter history
GET http://localhost:3200/api/1/counters/history/1/2020-12-01/2021-01-14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMzMyMjM3LCJleHAiOjE2MTM2OTIyMzd9.2uszWN7KDtAg0gYFo0yJpPrLK_TyMeLhmrC0ArmCogs

### get counter data range
GET http://localhost:3200/api/1/counters//daterange/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmZGZhMjRmZWI5NTc2NmM2Y2Y3MzdiMSIsImlkIjoiMzA1NDQwODk0IiwidXNlclR5cGUiOiIxIiwiZnVsbE5hbWUiOiJLb3JhbCBNYXpvciIsImFkZHJlc3MiOiJIaWJhdCBaaW9uIiwicGhvbmUiOiIrOTctMjUwNjkzMzcwNiIsImVtYWlsIjoia29yYWxtYXpvckBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEyLTIwVDE5OjEzOjE5LjAzOFoifSwiaWF0IjoxNjEzMDQyMzIwLCJleHAiOjE2MTM0MDIzMjB9.EfZv0pT5FG16E0cSiF0ECBB48cjF_sFkj4Z_4Sy1WQ8